<?php

namespace Database\Seeders;

use App\Models\Mindmap;
use App\Models\Subcategory;
use App\Models\Material;
use Illuminate\Database\Seeder;

class MindmapSeeder extends Seeder
{
    public function run(): void
    {
        $mindmapsData = [
            'bahasa-indonesia-sd' => [
                'title' => 'Bahasa Indonesia SD',
                'materials' => [
                    'Kosakata Dasar',
                    'Membaca Teks Sederhana',
                    'Membacakan Loud Reading',
                    'Mengenal Huruf dan Kata',
                    'Menulis Kalimat Dasar',
                    'Menulis Surat Sederhana',
                    'Pantun dan Syair',
                    'Pemahaman Cerita Rakyat',
                    'Tanda Baca',
                    'Puisi Anak',
                ],
                'layout' => [
                    ['x' => 340, 'y' => 120],
                    ['x' => 200, 'y' => 260],
                    ['x' => 440, 'y' => 260],
                    ['x' => 320, 'y' => 400],
                    ['x' => 700, 'y' => 340],
                    ['x' => 700, 'y' => 400],
                    ['x' => 700, 'y' => 460],
                    ['x' => 700, 'y' => 520],
                    ['x' => 140, 'y' => 400],
                    ['x' => 140, 'y' => 480],
                ],
                'connections' => [
                    ['from' => 0, 'to' => 1, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 0, 'to' => 2, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 0, 'to' => 3, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 3, 'to' => 4, 'style' => 'dotted', 'lineType' => 'curved',   'fromAnchor' => 'r', 'toAnchor' => 'l'],
                    ['from' => 3, 'to' => 5, 'style' => 'dotted', 'lineType' => 'curved',   'fromAnchor' => 'r', 'toAnchor' => 'l'],
                    ['from' => 3, 'to' => 6, 'style' => 'dotted', 'lineType' => 'curved',   'fromAnchor' => 'r', 'toAnchor' => 'l'],
                    ['from' => 3, 'to' => 7, 'style' => 'dotted', 'lineType' => 'curved',   'fromAnchor' => 'r', 'toAnchor' => 'l'],
                    ['from' => 3, 'to' => 8, 'style' => 'dashed', 'lineType' => 'straight', 'fromAnchor' => 'l', 'toAnchor' => 'r'],
                    ['from' => 8, 'to' => 9, 'style' => 'dashed', 'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                ],
            ],
            'matematika-sd' => [
                'title' => 'Matematika SD',
                'materials' => [
                    'Penjumlahan dan Pengurangan Bilangan Bulat',
                    'Perkalian dan Pembagian Dasar',
                    'Pecahan Sederhana',
                    'Geometri Dasar: Bangun Datar',
                    'Pengukuran Panjang dan Berat',
                    'Waktu dan Jam',
                    'Uang dan Mata Uang',
                    'Statistik Dasar: Diagram Batang',
                    'Bangun Ruang Sederhana',
                    'Soal Cerita Matematika SD',
                ],
                'layout' => [
                    ['x' => 360, 'y' => 100],
                    ['x' => 160, 'y' => 240],
                    ['x' => 360, 'y' => 240],
                    ['x' => 560, 'y' => 240],
                    ['x' => 100, 'y' => 380],
                    ['x' => 260, 'y' => 380],
                    ['x' => 420, 'y' => 380],
                    ['x' => 580, 'y' => 380],
                    ['x' => 200, 'y' => 520],
                    ['x' => 500, 'y' => 520],
                ],
                'connections' => [
                    ['from' => 0, 'to' => 1, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 0, 'to' => 2, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 0, 'to' => 3, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 1, 'to' => 4, 'style' => 'dashed', 'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 1, 'to' => 5, 'style' => 'dashed', 'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 2, 'to' => 6, 'style' => 'dotted', 'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 3, 'to' => 7, 'style' => 'dotted', 'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 4, 'to' => 8, 'style' => 'solid',  'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 7, 'to' => 9, 'style' => 'solid',  'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                ],
            ],
            'ipa-sd' => [
                'title' => 'IPA SD',
                'materials' => [
                    'Makhluk Hidup dan Lingkungan',
                    'Tubuh Manusia dan Kesehatan',
                    'Energi dan Perubahannya',
                    'Bumi dan Alam Semesta',
                    'Tanaman dan Hewan',
                    'Air dan Udara',
                    'Gaya dan Gerak',
                    'Sifat Benda',
                    'Ekosistem',
                    'Daur Ulang Sampah',
                ],
                'layout' => [
                    ['x' => 360, 'y' => 80],
                    ['x' => 120, 'y' => 220],
                    ['x' => 320, 'y' => 220],
                    ['x' => 560, 'y' => 220],
                    ['x' => 760, 'y' => 220],
                    ['x' => 120, 'y' => 380],
                    ['x' => 320, 'y' => 380],
                    ['x' => 560, 'y' => 380],
                    ['x' => 760, 'y' => 380],
                    ['x' => 440, 'y' => 520],
                ],
                'connections' => [
                    ['from' => 0, 'to' => 1, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 0, 'to' => 2, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 0, 'to' => 3, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 0, 'to' => 4, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 1, 'to' => 5, 'style' => 'dashed', 'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 2, 'to' => 6, 'style' => 'dashed', 'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 3, 'to' => 7, 'style' => 'dotted', 'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 4, 'to' => 8, 'style' => 'dotted', 'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 7, 'to' => 9, 'style' => 'solid',  'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                ],
            ],
            'ips-sd' => [
                'title' => 'IPS SD',
                'materials' => [
                    'Keluarga dan Kerabat',
                    'Sekolah dan Pendidikan',
                    'Masyarakat dan Lingkungan',
                    'Pekerjaan dan Profesi',
                    'Transportasi',
                    'Perdagangan',
                    'Peta dan Denah',
                    'Sejarah Kemerdekaan',
                    'Lembaga Sosial',
                    'Budaya Daerah',
                ],
                'layout' => [
                    ['x' => 360, 'y' => 80],
                    ['x' => 140, 'y' => 220],
                    ['x' => 340, 'y' => 220],
                    ['x' => 580, 'y' => 220],
                    ['x' => 140, 'y' => 380],
                    ['x' => 340, 'y' => 380],
                    ['x' => 580, 'y' => 380],
                    ['x' => 140, 'y' => 520],
                    ['x' => 360, 'y' => 520],
                    ['x' => 580, 'y' => 520],
                ],
                'connections' => [
                    ['from' => 0, 'to' => 1, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 0, 'to' => 2, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 0, 'to' => 3, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 1, 'to' => 4, 'style' => 'dashed', 'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 2, 'to' => 5, 'style' => 'dashed', 'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 3, 'to' => 6, 'style' => 'dashed', 'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 4, 'to' => 7, 'style' => 'dotted', 'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 5, 'to' => 8, 'style' => 'dotted', 'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 6, 'to' => 9, 'style' => 'dotted', 'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                ],
            ],
            'bahasa-inggris-sd' => [
                'title' => 'Bahasa Inggris SD',
                'materials' => [
                    'Alphabet and Phonics',
                    'Basic Greetings',
                    'Numbers and Counting',
                    'Colors and Shapes',
                    'Family Members',
                    'Animals',
                    'Fruits and Vegetables',
                    'Days of the Week',
                    'Simple Present Tense',
                    'Basic Vocabulary',
                ],
                'layout' => [
                    ['x' => 360, 'y' => 80],
                    ['x' => 120, 'y' => 220],
                    ['x' => 300, 'y' => 220],
                    ['x' => 500, 'y' => 220],
                    ['x' => 700, 'y' => 220],
                    ['x' => 120, 'y' => 380],
                    ['x' => 300, 'y' => 380],
                    ['x' => 500, 'y' => 380],
                    ['x' => 700, 'y' => 380],
                    ['x' => 400, 'y' => 520],
                ],
                'connections' => [
                    ['from' => 0, 'to' => 1, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 0, 'to' => 2, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 0, 'to' => 3, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 0, 'to' => 4, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 1, 'to' => 5, 'style' => 'dashed', 'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 2, 'to' => 6, 'style' => 'dashed', 'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 3, 'to' => 7, 'style' => 'dotted', 'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 4, 'to' => 8, 'style' => 'dotted', 'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 8, 'to' => 9, 'style' => 'solid',  'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                ],
            ],
            'matematika-smp' => [
                'title' => 'Matematika SMP',
                'materials' => [
                    'Aljabar Dasar',
                    'Persamaan Linear Satu Variabel',
                    'Teorema Pythagoras',
                    'Geometri: Lingkaran',
                    'Trigonometri Dasar',
                    'Statistik: Mean, Median, Modus',
                    'Peluang Dasar',
                    'Bangun Ruang: Kubus dan Balok',
                    'Sistem Persamaan Linear Dua Variabel',
                    'Fungsi Linear dan Kuadrat',
                ],
                'layout' => [
                    ['x' => 360, 'y' => 80],
                    ['x' => 120, 'y' => 220],
                    ['x' => 360, 'y' => 220],
                    ['x' => 600, 'y' => 220],
                    ['x' => 80,  'y' => 380],
                    ['x' => 240, 'y' => 380],
                    ['x' => 400, 'y' => 380],
                    ['x' => 600, 'y' => 380],
                    ['x' => 200, 'y' => 520],
                    ['x' => 520, 'y' => 520],
                ],
                'connections' => [
                    ['from' => 0, 'to' => 1, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 0, 'to' => 2, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 0, 'to' => 3, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 1, 'to' => 4, 'style' => 'dashed', 'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 1, 'to' => 5, 'style' => 'dashed', 'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 2, 'to' => 6, 'style' => 'dotted', 'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 3, 'to' => 7, 'style' => 'dotted', 'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 5, 'to' => 8, 'style' => 'solid',  'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 6, 'to' => 9, 'style' => 'solid',  'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                ],
            ],
            'bahasa-indonesia-smp' => [
                'title' => 'Bahasa Indonesia SMP',
                'materials' => [
                    'Teks Berita',
                    'Teks Deskripsi',
                    'Teks Eksposisi',
                    'Teks Prosedur',
                    'Teks Naratif',
                    'Puisi Lama dan Baru',
                    'Drama dan Teater',
                    'Artikel Opini',
                    'Surat Lamaran Kerja',
                    'Pidato Persuasif',
                ],
                'layout' => [
                    ['x' => 360, 'y' => 80],
                    ['x' => 120, 'y' => 220],
                    ['x' => 320, 'y' => 220],
                    ['x' => 520, 'y' => 220],
                    ['x' => 120, 'y' => 380],
                    ['x' => 320, 'y' => 380],
                    ['x' => 520, 'y' => 380],
                    ['x' => 720, 'y' => 300],
                    ['x' => 200, 'y' => 520],
                    ['x' => 460, 'y' => 520],
                ],
                'connections' => [
                    ['from' => 0, 'to' => 1, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 0, 'to' => 2, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 0, 'to' => 3, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 0, 'to' => 7, 'style' => 'dotted', 'lineType' => 'curved',   'fromAnchor' => 'r', 'toAnchor' => 'l'],
                    ['from' => 1, 'to' => 4, 'style' => 'dashed', 'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 2, 'to' => 5, 'style' => 'dashed', 'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 3, 'to' => 6, 'style' => 'dashed', 'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 4, 'to' => 8, 'style' => 'solid',  'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 6, 'to' => 9, 'style' => 'solid',  'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                ],
            ],
            'ipa-smp' => [
                'title' => 'IPA SMP',
                'materials' => [
                    'Sistem Pencernaan Manusia',
                    'Sistem Pernapasan',
                    'Struktur Tumbuhan',
                    'Struktur Hewan',
                    'Zat Aditif dan Adiktif',
                    'Bioteknologi',
                    'Energi dan Perubahannya',
                    'Hukum Newton',
                    'Listrik dan Magnet',
                    'Bumi dan Tata Surya',
                ],
                'layout' => [
                    ['x' => 360, 'y' => 80],
                    ['x' => 100, 'y' => 220],
                    ['x' => 280, 'y' => 220],
                    ['x' => 460, 'y' => 220],
                    ['x' => 640, 'y' => 220],
                    ['x' => 100, 'y' => 380],
                    ['x' => 280, 'y' => 380],
                    ['x' => 460, 'y' => 380],
                    ['x' => 640, 'y' => 380],
                    ['x' => 360, 'y' => 520],
                ],
                'connections' => [
                    ['from' => 0, 'to' => 1, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 0, 'to' => 2, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 0, 'to' => 3, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 0, 'to' => 4, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 1, 'to' => 5, 'style' => 'dashed', 'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 2, 'to' => 6, 'style' => 'dashed', 'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 3, 'to' => 7, 'style' => 'dotted', 'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 4, 'to' => 8, 'style' => 'dotted', 'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 8, 'to' => 9, 'style' => 'solid',  'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                ],
            ],
            'ips-smp' => [
                'title' => 'IPS SMP',
                'materials' => [
                    'Sosiologi Dasar',
                    'Geografi Indonesia',
                    'Sejarah Indonesia Kuno',
                    'Ekonomi Dasar',
                    'Pemerintahan Indonesia',
                    'Globalisasi',
                    'Demografi',
                    'Sumber Daya Alam',
                    'Perdagangan Internasional',
                    'Konflik Sosial',
                ],
                'layout' => [
                    ['x' => 360, 'y' => 80],
                    ['x' => 120, 'y' => 220],
                    ['x' => 320, 'y' => 220],
                    ['x' => 560, 'y' => 220],
                    ['x' => 120, 'y' => 380],
                    ['x' => 320, 'y' => 380],
                    ['x' => 560, 'y' => 380],
                    ['x' => 760, 'y' => 300],
                    ['x' => 220, 'y' => 520],
                    ['x' => 500, 'y' => 520],
                ],
                'connections' => [
                    ['from' => 0, 'to' => 1, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 0, 'to' => 2, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 0, 'to' => 3, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 0, 'to' => 7, 'style' => 'dotted', 'lineType' => 'curved',   'fromAnchor' => 'r', 'toAnchor' => 'l'],
                    ['from' => 1, 'to' => 4, 'style' => 'dashed', 'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 2, 'to' => 5, 'style' => 'dashed', 'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 3, 'to' => 6, 'style' => 'dashed', 'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 4, 'to' => 8, 'style' => 'solid',  'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 6, 'to' => 9, 'style' => 'solid',  'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                ],
            ],
            'bahasa-inggris-smp' => [
                'title' => 'Bahasa Inggris SMP',
                'materials' => [
                    'Present Continuous Tense',
                    'Past Tense',
                    'Future Tense',
                    'Modal Verbs',
                    'Prepositions',
                    'Conjunctions',
                    'Reading Comprehension',
                    'Writing Paragraphs',
                    'Listening Skills',
                    'Speaking Practice',
                ],
                'layout' => [
                    ['x' => 360, 'y' => 80],
                    ['x' => 120, 'y' => 220],
                    ['x' => 320, 'y' => 220],
                    ['x' => 560, 'y' => 220],
                    ['x' => 760, 'y' => 220],
                    ['x' => 120, 'y' => 380],
                    ['x' => 320, 'y' => 380],
                    ['x' => 560, 'y' => 380],
                    ['x' => 200, 'y' => 520],
                    ['x' => 500, 'y' => 520],
                ],
                'connections' => [
                    ['from' => 0, 'to' => 1, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 0, 'to' => 2, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 0, 'to' => 3, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 0, 'to' => 4, 'style' => 'dotted', 'lineType' => 'curved',   'fromAnchor' => 'r', 'toAnchor' => 'l'],
                    ['from' => 1, 'to' => 5, 'style' => 'dashed', 'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 2, 'to' => 6, 'style' => 'dashed', 'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 3, 'to' => 7, 'style' => 'dotted', 'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 5, 'to' => 8, 'style' => 'solid',  'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 7, 'to' => 9, 'style' => 'solid',  'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                ],
            ],
            'matematika-sma' => [
                'title' => 'Matematika SMA',
                'materials' => [
                    'Limit dan Turunan Fungsi',
                    'Integral Tak Tentu',
                    'Matriks dan Determinan',
                    'Vektor dalam Ruang Dimensi Tiga',
                    'Barisan dan Deret',
                    'Logika Matematika',
                    'Persamaan Lingkaran',
                    'Statistika Inferensial',
                    'Program Linear',
                    'Transformasi Geometri',
                ],
                'layout' => [
                    ['x' => 360, 'y' => 80],
                    ['x' => 120, 'y' => 220],
                    ['x' => 360, 'y' => 220],
                    ['x' => 600, 'y' => 220],
                    ['x' => 80,  'y' => 380],
                    ['x' => 260, 'y' => 380],
                    ['x' => 460, 'y' => 380],
                    ['x' => 660, 'y' => 380],
                    ['x' => 200, 'y' => 520],
                    ['x' => 520, 'y' => 520],
                ],
                'connections' => [
                    ['from' => 0, 'to' => 1, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 0, 'to' => 2, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 0, 'to' => 3, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 1, 'to' => 4, 'style' => 'dashed', 'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 1, 'to' => 5, 'style' => 'dashed', 'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 2, 'to' => 6, 'style' => 'dotted', 'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 3, 'to' => 7, 'style' => 'dotted', 'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 5, 'to' => 8, 'style' => 'solid',  'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 6, 'to' => 9, 'style' => 'solid',  'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                ],
            ],
            'bahasa-indonesia-sma' => [
                'title' => 'Bahasa Indonesia SMA',
                'materials' => [
                    'Teks Editorial',
                    'Teks Laporan Hasil Observasi',
                    'Teks Cerita Sejarah',
                    'Teks Ulasan',
                    'Teks Negosiasi',
                    'Puisi Kontemporer',
                    'Cerpen dan Novel',
                    'Kritik Sastra',
                    'Makalah Ilmiah',
                    'Proposal Penelitian',
                ],
                'layout' => [
                    ['x' => 360, 'y' => 80],
                    ['x' => 120, 'y' => 220],
                    ['x' => 320, 'y' => 220],
                    ['x' => 560, 'y' => 220],
                    ['x' => 120, 'y' => 380],
                    ['x' => 320, 'y' => 380],
                    ['x' => 560, 'y' => 380],
                    ['x' => 760, 'y' => 300],
                    ['x' => 220, 'y' => 520],
                    ['x' => 500, 'y' => 520],
                ],
                'connections' => [
                    ['from' => 0, 'to' => 1, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 0, 'to' => 2, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 0, 'to' => 3, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 0, 'to' => 7, 'style' => 'dotted', 'lineType' => 'curved',   'fromAnchor' => 'r', 'toAnchor' => 'l'],
                    ['from' => 1, 'to' => 4, 'style' => 'dashed', 'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 2, 'to' => 5, 'style' => 'dashed', 'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 3, 'to' => 6, 'style' => 'dashed', 'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 4, 'to' => 8, 'style' => 'solid',  'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 6, 'to' => 9, 'style' => 'solid',  'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                ],
            ],
            'ipa-sma' => [
                'title' => 'IPA SMA',
                'materials' => [
                    'Sel dan Jaringan',
                    'Genetika dan Hereditas',
                    'Evolusi',
                    'Ekologi',
                    'Kimia Dasar',
                    'Fisika Modern',
                    'Termokimia',
                    'Laju Reaksi',
                    'Hukum Termodinamika',
                    'Teknologi Nano',
                ],
                'layout' => [
                    ['x' => 360, 'y' => 80],
                    ['x' => 100, 'y' => 220],
                    ['x' => 280, 'y' => 220],
                    ['x' => 460, 'y' => 220],
                    ['x' => 640, 'y' => 220],
                    ['x' => 100, 'y' => 380],
                    ['x' => 280, 'y' => 380],
                    ['x' => 460, 'y' => 380],
                    ['x' => 640, 'y' => 380],
                    ['x' => 360, 'y' => 520],
                ],
                'connections' => [
                    ['from' => 0, 'to' => 1, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 0, 'to' => 2, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 0, 'to' => 3, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 0, 'to' => 4, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 1, 'to' => 5, 'style' => 'dashed', 'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 2, 'to' => 6, 'style' => 'dashed', 'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 3, 'to' => 7, 'style' => 'dotted', 'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 4, 'to' => 8, 'style' => 'dotted', 'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 8, 'to' => 9, 'style' => 'solid',  'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                ],
            ],
            'ips-sma' => [
                'title' => 'IPS SMA',
                'materials' => [
                    'Sosiologi Lanjut',
                    'Geografi Regional',
                    'Sejarah Dunia Modern',
                    'Ekonomi Makro',
                    'Sistem Politik Indonesia',
                    'Hubungan Internasional',
                    'Antropologi Sosial',
                    'Perbankan dan Keuangan',
                    'Pembangunan Ekonomi',
                    'Hukum dan Hak Asasi',
                ],
                'layout' => [
                    ['x' => 360, 'y' => 80],
                    ['x' => 120, 'y' => 220],
                    ['x' => 320, 'y' => 220],
                    ['x' => 560, 'y' => 220],
                    ['x' => 120, 'y' => 380],
                    ['x' => 320, 'y' => 380],
                    ['x' => 560, 'y' => 380],
                    ['x' => 760, 'y' => 300],
                    ['x' => 220, 'y' => 520],
                    ['x' => 500, 'y' => 520],
                ],
                'connections' => [
                    ['from' => 0, 'to' => 1, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 0, 'to' => 2, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 0, 'to' => 3, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 0, 'to' => 7, 'style' => 'dotted', 'lineType' => 'curved',   'fromAnchor' => 'r', 'toAnchor' => 'l'],
                    ['from' => 1, 'to' => 4, 'style' => 'dashed', 'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 2, 'to' => 5, 'style' => 'dashed', 'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 3, 'to' => 6, 'style' => 'dashed', 'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 4, 'to' => 8, 'style' => 'solid',  'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 6, 'to' => 9, 'style' => 'solid',  'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                ],
            ],
            'bahasa-inggris-sma' => [
                'title' => 'Bahasa Inggris SMA',
                'materials' => [
                    'Conditional Sentences',
                    'Passive Voice',
                    'Reported Speech',
                    'Narrative Text',
                    'Expository Text',
                    'Argumentative Essay',
                    'Business English',
                    'Academic Writing',
                    'TOEFL Preparation',
                    'IELTS Preparation',
                ],
                'layout' => [
                    ['x' => 360, 'y' => 80],
                    ['x' => 120, 'y' => 220],
                    ['x' => 320, 'y' => 220],
                    ['x' => 560, 'y' => 220],
                    ['x' => 760, 'y' => 220],
                    ['x' => 120, 'y' => 380],
                    ['x' => 320, 'y' => 380],
                    ['x' => 560, 'y' => 380],
                    ['x' => 200, 'y' => 520],
                    ['x' => 520, 'y' => 520],
                ],
                'connections' => [
                    ['from' => 0, 'to' => 1, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 0, 'to' => 2, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 0, 'to' => 3, 'style' => 'solid',  'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 0, 'to' => 4, 'style' => 'dotted', 'lineType' => 'curved',   'fromAnchor' => 'r', 'toAnchor' => 'l'],
                    ['from' => 1, 'to' => 5, 'style' => 'dashed', 'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 2, 'to' => 6, 'style' => 'dashed', 'lineType' => 'straight', 'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 3, 'to' => 7, 'style' => 'dotted', 'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 5, 'to' => 8, 'style' => 'solid',  'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                    ['from' => 7, 'to' => 9, 'style' => 'solid',  'lineType' => 'curved',   'fromAnchor' => 'b', 'toAnchor' => 't'],
                ],
            ],
        ];

        foreach ($mindmapsData as $subcategorySlug => $data) {
            $subcategory = Subcategory::where('slug', $subcategorySlug)->first();
            if (!$subcategory) continue;

            // Ambil material IDs berdasarkan judul
            $nodeList = [];
            foreach ($data['materials'] as $i => $materialTitle) {
                $material = Material::where('title', $materialTitle)
                    ->where('subcategory_id', $subcategory->id)
                    ->first();
                $nodeList[] = [
                    'id'         => 'node-' . ($i + 1),
                    'materialId' => $material ? $material->id : null,
                    'title'      => $materialTitle,
                    'x'          => $data['layout'][$i]['x'],
                    'y'          => $data['layout'][$i]['y'],
                    'type'       => 'material',
                    'completed'  => false,
                    'style'      => [],
                ];
            }

            // Bangun connections
            $connections = [];
            foreach ($data['connections'] as $ci => $conn) {
                $connections[] = [
                    'id'         => 'conn-seed-' . $ci,
                    'from'       => 'node-' . ($conn['from'] + 1),
                    'fromAnchor' => $conn['fromAnchor'],
                    'to'         => 'node-' . ($conn['to'] + 1),
                    'toAnchor'   => $conn['toAnchor'],
                    'style'      => $conn['style'],
                    'lineType'   => $conn['lineType'],
                ];
            }

            Mindmap::updateOrCreate(
                ['reference_id' => $subcategory->id],
                [
                    'title'     => $data['title'],
                    'structure' => ['nodes' => $nodeList, 'connections' => $connections],
                    'status'    => 'publish',
                ]
            );
        }
    }
}
